spring:
  datasource:
    name: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/mamont_solutions
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # This will create table automatically in your database
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: PostgreSQLDialect